opscenter:
  container_name: opscenter
  image: bochen/opscenter:5.2.2
  ports:
    - "8888:8888"

cassandra:
  container_name: cassandra
  image: bochen/cassandra:3.0.0
  ports:
    - "9042:9042"
    - "9160:9160"
    - "7199:7199"
  environment:
    CASSANDRA_CLUSTER_NAME: Bochen
  links:
    - opscenter

scalable-cassandra:
  image: bochen/cassandra:3.0.0
  environment:
    CASSANDRA_CLUSTER_NAME: Bochen
  links:
    - opscenter
    - cassandra

elasticsearch:
  container_name: elasticsearch
  image: bochen/elasticsearch:2.1.0
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    ES_CLUSTER_NAME: Bochen

scalable-elasticsearch:
  image: bochen/elasticsearch:2.1.0
  environment:
    ES_CLUSTER_NAME: Bochen
    ES_ENABLE_CLUSTER: 1
  links:
    - elasticsearch:es

kibana:
  container_name: kibana
  image: bochen/kibana:4.3.0
  ports:
    - "5601:5601"
  links:
    - elasticsearch:es

zookeeper:
  container_name: zookeeper
  image: bochen/zookeeper:3.4.6
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

kafka:
  container_name: kafka
  image: bochen/kafka:0.8.2.2
  ports:
    - "9092:9092"
    - "9898:9898"
  environment:
    KAFKA_LOG_RETENTION_HOURS: 1
    KAFKA_LOG_RETENTION_BYTES: 314572800
  links:
    - zookeeper:zk

storm-nimbus:
  container_name: storm-nimbus
  image: bochen/storm-nimbus:0.10.0
  ports:
    - "3772:3772"
    - "3773:3773"
    - "6627:6627"
  links:
    - zookeeper:zk

storm-ui:
  container_name: storm-ui
  image: bochen/storm-ui:0.10.0
  ports:
    - "9999:8080"
  links:
    - storm-nimbus:nimbus
    - zookeeper:zk

storm-supervisor:
  image: bochen/storm-supervisor:0.10.0
  ports:
    - "8000"
  links:
    - storm-nimbus:nimbus
    - zookeeper:zk
    - kafka
    - cassandra
    - elasticsearch:es
