es.logger.level: INFO
rootLogger: ${es.logger.level}, console

logger:
  action: DEBUG
  deprecation: INFO
  org.apache.http: INFO
  gateway: DEBUG
  index.gateway: DEBUG
  indices.recovery: DEBUG
  discovery: TRACE
  index.search.slowlog: TRACE
  index.indexing.slowlog: TRACE

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{dd-MM-yyyy HH:mm:ss}] [%c] [%p] %m%n"
